### ISSUE TITLE
Importar requests

### ISSUE THREAD

**Issue by santiagocruzb** [IIC2233-2016-1/syllabus#617]
Hola!

```
import base64
import json
import requests
```

Al momento de importar `requests` me muestra el error de que no es capaz de encontrar un atributo dentro de un archivo.

```
Traceback (most recent call last):
  File "/Users/SantiagoCruzB/Documents/SantiagoCruzB_Pythons/santiagocruzb-iic2233-repo/Tareas/T07/Pruebas/pruba.py", line 4, in <module>
    import requests
  File "/usr/local/lib/python3.5/site-packages/requests/__init__.py", line 53, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "/usr/local/lib/python3.5/site-packages/requests/packages/__init__.py", line 27, in <module>
    from . import urllib3
  File "/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/__init__.py", line 10, in <module>
    from .connectionpool import (
  File "/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 2, in <module>
    import logging
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/logging/__init__.py", line 26, in <module>
    import sys, os, time, io, traceback, warnings, weakref, collections
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/traceback.py", line 5, in <module>
    import linecache
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/linecache.py", line 11, in <module>
    import tokenize
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/tokenize.py", line 40, in <module>
    __all__ = token.__all__ + ["COMMENT", "tokenize", "detect_encoding",
AttributeError: module 'token' has no attribute '__all__'
```

Pero el módulo `token` si tiene el atributo `__all__`  (en internet no sale mucho sobre este problema)

![screen shot 2016-06-22 at 5 05 05 pm](https://cloud.githubusercontent.com/assets/13748925/16283623/84a0ab50-389b-11e6-8771-460a52b07e5f.png)

Ayuda! Muchas gracias

**Comment by fgvenegas** [comment]
Googleando encontre [esto](http://www.gossamer-threads.com/lists/python/python/1180992) quizas te sirva

**Comment by santiagocruzb** [comment]
Tenía otro archivo con nombre token.py y chocaba, muchas gracias!
